apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aysa-demo-app
  name: pipelines-aysa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines-aysa-demo
  template:
    metadata:
      labels:
        app: pipelines-aysa-demo
    spec:
      containers:
        - image: quay.io/openshift-pipeline/vote-api:latest
          imagePullPolicy: Always
          name: pipelines-vote-api
          ports:
            - containerPort: 9000
              protocol: TCP
